### ISSUE TITLE
[Feature]  Task doing

### ISSUE THREAD

**Issue by adilaxmdv** [mammadkhan/reactKanban#1]
I think when tasks on doing we can select to do or not. when we place task to finished place  make all doed

**Comment by mammadkhan** [comment]
Hi.

Thanks for suggestion.

**Comment by adilaxmdv** [comment]
> Hi.
> 
> Thanks for suggestion.

Why closed ? I think u are beginner github user. Open this issue give it tag for help wanted

**Comment by mammadkhan** [comment]
Why would  I need help.Your suggestion is out of scope of this challenge which I completed.Columns and boards can be named and structured by user however they want.If you want to see feature proposed by you in website you can easly fork this repo and implement it by yourself.
